// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace webrtc {

struct MixerSource final {

    static constexpr int32_t TYPE_FILE = 1;

    static constexpr int32_t TYPE_RECORD = 2;

    int32_t type;
    int32_t ssrc;
    float volume_left;
    float volume_right;
    bool enabled;
    bool streaming;
    bool playback;
    bool remix;
    std::string path;
    int32_t sample_rate;
    int32_t channel_num;

    MixerSource(int32_t type_,
                int32_t ssrc_,
                float volume_left_,
                float volume_right_,
                bool enabled_,
                bool streaming_,
                bool playback_,
                bool remix_,
                std::string path_,
                int32_t sample_rate_,
                int32_t channel_num_)
    : type(std::move(type_))
    , ssrc(std::move(ssrc_))
    , volume_left(std::move(volume_left_))
    , volume_right(std::move(volume_right_))
    , enabled(std::move(enabled_))
    , streaming(std::move(streaming_))
    , playback(std::move(playback_))
    , remix(std::move(remix_))
    , path(std::move(path_))
    , sample_rate(std::move(sample_rate_))
    , channel_num(std::move(channel_num_))
    {}
};

}  // namespace audio_mixer
