// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio_mixer.djinni

#include "modules/backing_track/mixer_source.h"  // my header

namespace webrtc {

int32_t constexpr MixerSource::TYPE_FILE;

int32_t constexpr MixerSource::TYPE_RECORD;

}  // namespace audio_mixer
