#!/usr/bin/env python
# Copyright (c) 2011 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys

supplement_gypi = """#!/usr/bin/env python
# This file is generated by %s.  Not for check-in.
# Please see the WebRTC DEPS file for details.
{
  'variables': {
    'build_with_chromium': 0,
    'inside_chromium_build': 0,
  }
}
"""

def main(argv):
  open(argv[1], 'w').write(supplement_gypi % argv[0])

if __name__ == '__main__':
  sys.exit(main(sys.argv))
